language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-23.0.0
    - android-23
    - extra-android-support
    - extra-android-m2repository

script:
  - ./gradlew assemble
  - ./gradlew test
