language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.0
    - android-23
    - extra-android-support
    - extra-android-m2repository

script:
  - ./gradlew build
  - ./gradlew test
