language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28
    - extra-android-support
    - extra-android-m2repository

script:
  - ./gradlew assembleDebug
  - ./gradlew testGooglePlayDebug
  - ./gradlew testFlossDebug
