files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    translate_attributes: 0
  - source: /app/src/main/res/values/arrays.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
  - source: /app/src/main/play/en-US/*/*
    translation: /app/src/main/play/%locale%/listing/%original_file_name%
  - source: /app/src/main/play/en-US/*
    translation: /app/src/main/play/%locale%/%original_file_name%
